[build-system]
requires = [
  # sync with setup.py until we discard non-pep-517/518
  'setuptools>=42.0',
  'setuptools-scm[toml]>=3.4',
  'wheel',
]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]

[tool.black]
skip_string_normalization = '1'
